---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  namespace: riju-server
  name: riju-server
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
    - host: "{{ .networking.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: riju-server
                port:
                  number: 80
  tls:
    - hosts:
      - "{{ .networking.domain }}"
      secretName: riju-server-tls
